environment:
  matrix:
    - vs_version: 14

os: Visual Studio 2015

configuration:
  - Release

platform:
  - x86
  - x64

clone_folder: C:\projects\mue-win-deps

install:
  - set TARGET_ARCH=64
  - if /I "%platform%"=="x86" set TARGET_ARCH=32
  - .\settings.bat "TARGET_ARCH=%TARGET_ARCH%" "BUILD_TYPE=%configuration%" "TOOLS_VERSION=%vs_version%.0"
  - scripts\build_zlib.bat
  - scripts\build_protobuf-2.6.1.bat
  #- scripts\build_bdb.bat
  #- scripts\build_miniupnpc.bat
  #- scripts\build_qrencode.bat

build: off
artifacts:
  - path: mue-win-deps\bin
test: off
deploy: off
